### ISSUE TITLE
Бесконечный цикл ререндеринга

### ISSUE THREAD

**Issue by livingroot** [Firnis/yandex-metrica-ab-react#10]
В этом месте получается бесконечный цикл, из-за склеивания конфига. Полагаю, что внесли какие-то изменения в exp.js, которые затрагивают переменную config, поэтому эта проблема не возникала раньше.

https://github.com/Firnis/yandex-metrica-ab-react/blob/main/src/useExperiments.ts#L25

**Comment by Firnis** [comment]
Иправил https://github.com/Firnis/yandex-metrica-ab-react/commit/023b65fd7578f79fa9c02eef2ba7652187f0d10a
